### ISSUE TITLE
Component not rendering new props

### ISSUE THREAD

**Issue by bar0191** [jstejada/react-typist#29] opened 2017-06-08 05:46 UTC
Hello,

I have been playing with your module, and I have come across an issue. I am trying to create a dynamically changing header component that will change the string of the header every 4 seconds. I am able to get tags to change dynamically just fine with my component, but using typist I get the first prop (beginning of an array of strings) and then it does not receive the next props.

I did notice in your module, you do not have `componentWillReceiveProps(nextProps)` and this may be the reason it is not changing when a new prop is rendered. I'm honestly not really sure, wondering if I could get your input. 

Thanks.

**Comment by jstejada** [comment] 2017-10-16 05:13
Thanks for reporting this! I'll look into this soon

**Comment by xuezhma** [comment] 2017-11-17 20:28
Make `componentWillReceiveProps` to repeat `componentDidMount` will prob fix this.

Meanwhile a simple work around is to unmount the component then render a new instance with new props.

**Comment by jpsear** [comment] 2017-12-13 11:15
Just as a heads up, I locally tried tweaking the module to enable this. I got it to work, but it wasn't very robust — it had some odd behaviour on scroll etc. Complex animation is not really my bag! 

Anyway, I ended up using a "mount, unmount" pattern to get the job done, but here is the code I added to the `Typist` component (once again, this doesn't work properly — **not production code**):

```js
  componentDidMount() {
    this.mounted = true;
    this.startAnimation(this.props);
  }

  componentWillReceiveProps(nextProps) {
    this.linesToType = [];
    this.startAnimation(nextProps);
  }

  startAnimation({ children, startDelay }) {
    if (children) {
      this.setState({ isDone: false });
      this.linesToType = utils.extractTextFromElement(children);

      if (startDelay > 0 && typeof window !== 'undefined') {
        setTimeout(this.typeAllLines.bind(this), startDelay);
      } else {
        this.typeAllLines();
      }
    } else {
      this.onTypingDone();
    }
  }
```

**Comment by linonetwo** [comment] 2017-12-20 06:40
Sometimes, you can simply give the component a key, then it will remount if key changes.

**Comment by jstejada** [comment] 2017-12-20 06:45
Thanks for the input and the workarounds everyone!! And sorry again for the delay in getting back to you!

The root cause of the issue is definitely that `componentWillReceiveProps` isn't implemented. The main problem I initially imagined was that I wasn't sure if it was desirable to restart the animation every time new props were received, or only in specific cases.

I'll give it some additional thought, but I think I'll have a solution soon. Any input on this would also be appreciated! :)

**Comment by frehner** [comment] 2018-01-24 23:36
I was able to get this to work doing the following:

```jsx
  <Typist startDelay={1000} avgTypingDelay={120}>
      { frameworks.map(framework => (
        <span key={framework}>
          <Typist.Delay ms={500}/>
          {framework}
          <Typist.Backspace count={framework.length} delay={1000}/>
        </span>
      ))}
```
this will only ever show one item in the array at a time, and then erases the item and types out the next one.

The only thing left is how to get it to start over from the start when it reaches the end. May just have to unmount and remount it

**Comment by stevengeorgeharris** [comment] 2018-02-02 10:51
```
<Typist key={ yourText } >
```

Works just fine.

**Comment by jstejada** [comment] 2018-08-27 03:47
hey everyone, I don't think there's anything actionable to do here, given that there's no straightforward way to tell when the animation should be restarted when new props are received, and doing so could break current usages.

I think using `key` to allow developers to remount Typist when they need to sounds like a good compromise in the meantime, so closing this for now

**Closed by jstejada** 2018-08-27 03:47 UTC
